### PR TITLE
Improve tab title text style

### PR DESCRIPTION
**Pull request by Livven**
Makes it closer to how it is in the original Tab Center.

### CODE REVIEW

**Comment by eoger** [comment]
Waiting on a designer (Mozilla related would be better since we're trying to integrate with the browser style) to review this.

**Comment by yfdyh000** [comment]
See also #84.

**Comment by eoger** [comment]
Would you mind posting a screenshot?

**Comment by eoger** [comment]
Let's keep the style close to the Firefox UI. Closing for now.

**Pull request closed without merging**
