### PR TITLE
Add zh-CN locale

### PR DESCRIPTION
**Pull request by yfdyh000**
Note: I translated the "Redux" to translation of "Ultimate" (终极), because Redux may not be cool enough. Or, the translation should keep original text?

### CODE REVIEW

**Comment by eoger** [comment]
Are you sure this works? From [the docs](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization#Providing_localized_strings_in__locales), it seems like the separator must be an underscore.

**Comment by yfdyh000** [comment]
Yes, I sure this works in 56.0a1 (2017-06-15) and you can try it with general.useragent.locale to zh-CN in about:config. I don't know well this statement from that document.

**Comment by eoger** [comment]
Just to be safe, can you modify it for an underscore anyway? In the future they might be more strict and this would break the translation.

**Comment by yfdyh000** [comment]
Renamed.

**Comment by eoger** [comment]
Perfect thank you

**Pull request merged**
