### PR TITLE
Implement proper pinned tabs

### PR DESCRIPTION
**Pull request by Livven**
See #27, uses the approach outlined there. Some notes:

- Off by default, turn on in settings.
  - Wording is awkward ("pin pinned tabs"). Also awkward in code.
- All the different states should be handled.
  - Shrinked and unshrinked tab list states don't affect pinned tabs.
    - Dynamic updating of shrink status (`maybeShrinkTabs`) needs to be adjusted. Minor issue in my opinion.
  - Pinned tabs revert to the previous/"normal" design in filtered mode.
- Most of the CSS is auto-generated using Sass.
  - Sass compilation is integrated into the existing npm scripts, should "just work" and not cause any issues.
  - There are limits on the supported number of pinned tabs (60) and tab list width (600px).
    - A pinned tab in the default Firefox tab bar and style is about 34px wide, so 60 pinned tabs would be about 2040px wide. Needless to say this would already cause issues for most users using the default tab bar.
    - Sidebar width seems to be restricted to 432px by Firefox, but since that number could change in the future I added some safety room. In any case it will work with even wider sidebars, but just not utilize the full width.
- Design should be improved, but I think it's good enough for now especially for being off by default.
  - The active tab highlight (`.tab-context`) should probably be changed in some way.
  - There are slight positional glitches due to using `translate` causing some borders to not show up. Probably only affects high-dpi configurations.

### CODE REVIEW

**Comment by eoger** [comment]
I'm sorry but this is not gonna work for me.
Like it said in my previous comment https://github.com/eoger/tabcenter-redux/issues/27#issuecomment-309605632 this feels way too hackish to me.
I'm concerned about multiple things: the ability to maintain this, the fact that this unusual way of doing things might bite us in the future, the performance consequences of having an inflated CSS, the increased complexity of the build chain and the reliance on a magic number (60 tabs).
As it is, I will not merge this.

**Comment by Livven** [comment]
Can I convince you otherwise?

> way too hackish

Only conceptually. If the code is clear and simple, and there's simply _not that much of it_ compared to the alternative approach, being *conceptually* hacky is not necessarily a drawback. Especially considering, as you said, the alternative is using a separate container which means potentially duplicating all of the tab logic; even if that is less "hacky" I wouldn't call it any more elegant or maintainable.

> the ability to maintain this

As in the previous point, I don't think it gets any _more_ maintainable than this. There's no duplication or even modification to the tab logic, the changes are almost exclusively to the CSS, parts of which will be required for any other approach as well anyway.

> the fact that this unusual way of doing things might bite us in the future

Sure, it's unusual. But again, the code, even the concept, is so simple. Being conceptually hacky doesn't mean it's complicated, or hard to understand, or hard to maintain, or that there is a better way.

> the performance consequences of having an inflated CSS

We can discuss the previous points (and they are very valid!) but let's not throw stuff like this out. Sure, I wouldn't write that many rules by hand, but this seems to be a classic case of premature optimization; in fact a look at nytimes.com leads to a 77 KB minified CSS file, which just happens to be the same size as the generated unminified CSS here; Gmail has one that's over 1 MB. Also keep in mind many of the rules are behind media queries so they aren't even always active.

Also, practically speaking, I usually keep several hundred tabs open and have always struggled with the performance of the tab bar in Firefox. Any performance issues at this point are almost always trivial things that no one simply cares about, e.g. #58 and similarly in the original Tab Center, showing the scrollbar only on hover which lead to the same issue. These are the real performance killers, and the only way to find them is by e.g. profiling and not by premature optimization like this.

Concretely, try pinning as many tabs as you can. Even resize the sidebar. You're not going to get any performance issues, in fact you'll get cool animations as the pinned icons shift around. Know how to get performance issues? Try opening several hundred tabs. Then resize the sidebar. _That's_ going to be _really_ laggy.

> the increased complexity of the build chain

`npm install` and `npm run dev`.

> the reliance on a magic number (60 tabs)

Magic numbers exist whether you explicitly encode them or not. The number of pinned tabs in default Firefox is also limited by the width of each pinned tab and the fact they don't scroll. I can totally understand still not liking this, I certainly don't like it either, but realistically it's just bikeshedding.

---

Also keep in mind this is the [most-requested](https://github.com/bwinton/TabCenter/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) feature from the original Tab Center. It literally breaks pinned tabs. I mean, why are they called pinned tabs?

I understand your concerns but hope we can find a way to resolve this.

**Comment by Livven** [comment]
To simplify, as you [noted yourself](https://github.com/eoger/tabcenter-redux/issues/27#issuecomment-309605632), this approach is probably much simpler than the less hacky alternative. I mean, it literally does not require any modification to any existing (or future!) tab handling code; it doesn't get any better than that.

Have you tried drag-and-drop? It just works. I have no idea how, but it does.

---

My conclusion is that, while this approach is obviously _kind of weird_, it's actually much better once you think everything through, since it is less code _and_ makes less changes to existing code.

Look at it this way: it's like automating a repetitive task. For the price of some upfront work, you get to do much less work in the long run. If that's not the definition of maintainability then I don't know what is; in this case there's not even any more upfront work, just a small mental hurdle to overcome.

**Comment by Keith94** [comment]
I think this is a great improvement for pinned tabs, both functionally and visually; myself (and many others) have been wanting to see this added to the original add-on since it first launched.

I recall a similar WebExtension (Tree Tabs) displays the pinned tabs in a similar fashion... I wonder if their implementation is any more "preferred" or can be used here in some way? Just throwing that out there in case it helps!

**Comment by eoger** [comment]
I did some [digging in the Firefox code](http://searchfox.org/mozilla-central/source/browser/base/content/tabbrowser.xml#6380), it might be interesting to investigate going that way.

**Comment by eoger** [comment]
Superseded by https://github.com/eoger/tabcenter-redux/pull/106, we finally have them :)

**Pull request closed without merging**
