### PR TITLE
Add Pinned Tab support.

### PR DESCRIPTION
**Pull request by bwinton**
It was slightly tricky to get stuff where I wanted it, but not _too_ bad.

Future additions could add some optimizations like not getting the screenshot for pinned tabs, or put the pinned tabs in their own section that doesn't scroll, but this seems good for now…  😉

### CODE REVIEW

**Comment by Keith94** [comment]
How does this compare to #95?

**Comment by bwinton** [comment]
I haven't looked into #95 in depth, but from what I see, it's way simpler; doesn't add a whole CSS build step; and doesn't have arbitrary limits on the number of pinned tabs or tab list width.  It adds a total of eight lines of code, instead of 950, and doesn't generate unknown amounts of CSS.

**Comment by eoger** [comment]
This looks fine to me, however since this is quite a big change, I wonder if this should be behind an option enabled by default, so users can go back to the legacy/original layout?
Would it be hard to conserve these two layouts?

**Comment by bwinton** [comment]
Perhaps not, but I say "Be bold!"  😉  Fewer options means less combinations to test when you add new features…

**Comment by Livven** [comment]
This does not keep pinned tabs in their own section that doesn't scroll (@Keith94) which I think is the whole point of pinned tabs... and also I don't think it's fair to count the changes to the package-lock.json file 😆

(That said obviously this PR is simpler because it does way less. Try implementing the same functionality for a fair comparison :)

Also this doesn't show favicons for unpinned tabs for me though that could just be an issue on my end.

**Comment by Livven** [comment]
Also another point I agree with @bwinton that keeping the original layout is unnecessary. There is no reason to provide an option that basically makes pinned tabs behave liked unpinned tabs; if you wanted the normal unpinned layout you'd simply, well, not pin the tab.

As far as I can tell the only reason the original layout even exists is because the proper behavior was deemed too difficult to implement (?).

**Comment by eoger** [comment]
I'm not a huge fan of the design when for example only one pinned tab is shown, although I do understand that this is inherent of the way this was implemented (only CSS rules.)

yvoiafc

PS: I confirm that the compact mode looks broken to me too.

**Comment by eoger** [comment]
Awesome new version! Merged in https://github.com/eoger/tabcenter-redux/commit/ddccc839807e62aa74857bc20e0ebcedc3a656ff, thanks a lot :)

**Comment by mnoorenberghe** [comment]
I just got the update and this is awesome!

**Pull request closed without merging**
