### PR TITLE
Add Tab Tree “focus last active tab” features

### LINKED ISSUE #263: Feature request: Switch to previously used tab when clicking on active tab
I propose an optional feature - clicking on active tab switches to previously selected tab (à la Tab flip feature of pre-quantum Tab Tree addon).

It's quite productive feature to have, as it saves time when cycling through a couple of tabs without having to resort to ctrl+tab shortcut.

Naive (but seemingly working) implementation example attached.
[tabflip.diff.txt](https://github.com/eoger/tabcenter-redux/files/1485478/tabflip.diff.txt)

### PR DESCRIPTION
**Pull request by ariasuni**
- Focus last active tab when clicking on currently focused tab (Fix #263)
- Add option to switch to last active tab when closing current tab

### CODE REVIEW

**Comment by eoger** [comment]
Sorry I think this feature is too niche for me to accept.  
Like I said in https://github.com/eoger/tabcenter-redux/issues/263#issuecomment-347055961, maybe a JS api that power-users could use to add alter the extension behavior (ala CSS editor) would be the answer.

**Comment by ariasuni** [comment]
Are you interesting by this particular change?

> Note: now a tab is focused on click release instead of press, so moving a tab doesn’t change focus

**Comment by eoger** [comment]
Sorry about the delay, IIUC the current native Firefox behavior is to focus the tab on mousedown, which is what we are doing currently.

**Comment by ariasuni** [comment]
I couldn’t make the code work with the current version, and I don’t understand most of the code so I guess I won’t work on it anymore.

In the meantime, I developed [Tab Flip for Tree Style Tab](https://addons.mozilla.org/firefox/addon/tab-flip-for-tree-style-tab/), an addon that add this feature to Tree Style Tab.

**Pull request closed without merging**
