### PR TITLE
Firefox Photon Design

### LINKED ISSUE #170: Photon Theme Colors
With the release of Firefox 57, the theme colors are changing and the current CSS no longer matches the colors of Firefox, especially in Dark mode. Should we add new theme options for Photon or simply replace the current themes with ones that are Photon compliant?

Here's a reference for the new theme colors: http://design.firefox.com/photon/visual/color.html#themes

### PR DESCRIPTION
**Pull request by Ivan0xFF**
Closes #170

This is probably still needs more work, specially the light theme. The light theme is currently following the MacOS Light Theme colors.

The colors listed for the light theme on the Photon Design website don't match the Mac OS light theme at all, I'm not sure what to do about that. Do we follow the listed colors or try and emulate a particular OSes colors?

Submitting now to get some early feedback on the changes included, particularly the CSS restructuring to make the dark and light themes mostly variable changes.

### CODE REVIEW

**Comment by Ivan0xFF** [comment]
I double checked Windows, the Photon Light them colors listed here: http://design.firefox.com/photon/visuals/color.html are definitely off. Maybe they're out of date? 

I'm using the colors currently found on the FF 57 Beta Light Theme for this PR.

**Comment by Ivan0xFF** [comment]
Updated pull request, including container colors per this blog post: https://hacks.mozilla.org/2017/10/containers-for-add-on-developers/

**Comment by Ivan0xFF** [comment]
One more thing to discuss. The menus are not themed dark in Firefox when using the dark theme. Should we be coloring them dark at all?

**Comment by Ivan0xFF** [comment]
Alright, that's about done. Let me know what you think!

**Comment by eoger** [comment]
Great work, however I probably don't have a good enough taste to say if this looks good/integrated well with Firefox. I'd like try to grab the attention of a Firefox designer to check if this looks right.
I'm also wondering if we should have platform-specific CSS.

**Comment by Keith94** [comment]
@shorlander worked on the legacy Tab Center styling, maybe he can take a look?

**Comment by eoger** [comment]
I merged a part of this PR in https://github.com/eoger/tabcenter-redux/commit/ae150fe8c18865581fba7281122d8078bff996ba
I did not really agree with the changes in tab colors, so I kept them away. I'd still like a designer to chime in here.
Also the vars refactor were more than welcomed!

**Comment by Ivan0xFF** [comment]
0.5.0 is an awesome improvement! Still, the colors of dark mode don't match the colors of FF 57 dark mode. Is that what you want a designer to chime in on?

**Comment by eoger** [comment]
I was mostly thinking about the "light" theme colors which didn't really match the interface for me!

**Comment by eoger** [comment]
Let's reopen this once we have a clear design direction.

**Pull request closed without merging**
