### PR TITLE
Allow contextmenu on earchbox-input

### PR DESCRIPTION
**Pull request by yfdyh000**

### CODE REVIEW

**Comment by Keith94** [comment]
I noticed pasting a word in the search box (from the menu) requires pressing Enter to filter the tabs, but with Ctrl+V it filters automatically. Any fix for that?

**Comment by yfdyh000** [comment]
@Keith94 Thanks for your report, fixed.

**Comment by Keith94** [comment]
Looks good 👍

**Comment by eoger** [comment]
Merged, thanks!

**Pull request closed without merging**
