### PR TITLE
Disable ESLint linebreak rule

### PR DESCRIPTION
**Pull request by Livven**
Unnecessary since Git automatically handles CRLF conversion on Windows if set up correctly, in which case the ESLint rule only leads to annoying errors on every line.

Plus it's not like the ESLint rule by itself can prevent CRLFs from being committed, so there's no real loss of functionality either.

### CODE REVIEW

**Comment by eoger** [comment]
"if set up correctly" is what bothers me, I'd rather keep this line in order to avoid bad commits from contributors, but I could be swayed.

**Comment by Livven** [comment]
"Set up correctly" simply means using the default options when installing Git on Windows so that should apply to most. And anyone who is using Windows and for whatever reason does not have that set up correctly probably doesn't know to run ESLint either.

However I just added another commit which forces the correct behavior (to always commit LF line endings) on a per-repo basis which is even better than before :)

**Comment by eoger** [comment]
I'm okay with just the .eslintrc file changes if Git for windows default to auto crlf.
Apparently, it seems that in some cases git can get confused if text=auto is set in .gitattributes.

**Comment by Livven** [comment]
You mean treating binary files as text and corrupting them? That's certainly a risk but it also exists with `autocrlf=true` on Windows, which is indeed the default.

Anyway I reverted the commit. As long as I don't have to see errors for every line I'm happy :)

**Comment by Livven** [comment]
Actually to prevent any potential corruption we could explicitly declare file endings in the `.gitattributes` like this:

```
*.js text
```

It wouldn't cover all possible text files but since ESLint doesn't either it would still be a straight improvement without any drawbacks. Thoughts?

**Comment by eoger** [comment]
Merged https://github.com/eoger/tabcenter-redux/commit/930796a721cb94b799563d2071bc8b539e550f06, thanks

**Pull request closed without merging**
