### PR TITLE
Add web-ext, and some scripts to use it.

### PR DESCRIPTION
**Pull request by bwinton**
I don't like installing `web-ext` globally, and I like it when stuff just runs for me automatically…  🙂

### CODE REVIEW

**Comment by eoger** [comment]
Heh, only one problem with me, web-ext assumes that you have installed Firefox release by default.
`Running web extension from /Users/eoger/tabcenter-redux/src
Error: spawn /Applications/Firefox.app/Contents/MacOS/firefox-bin ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)`

**Comment by bwinton** [comment]
If you don't have Firefox in a standard place, you can set `$WEB_EXT_FIREFOX` to the path of the binary you want to use.  :)

**Comment by eoger** [comment]
`WEB_EXT_FIREFOX=/Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin npm run dev` works for me. Thanks!

**Comment by eoger** [comment]
Do you mind also making a PR for the README.md file?

**Comment by bwinton** [comment]
Sure!

**Pull request merged**
