### PR TITLE
Add a drop shadow after pinned tabs if not scrolled to top.

### LINKED ISSUE #240: Show a drop shadow between pinned and non-pinned tabs
I've sometimes thought "where did all my tabs go" just because it looked like a continuous list. Firefox has a nice subtle drop shadow between pinned and non-pinned tabs, which disappears if you are at the start of the tab list. Maybe this could be added here as well?

image

### PR DESCRIPTION
**Pull request by thomcc**
Also, fixes that there's no visible border between pinned and normal
tabs in compact mode (in general, but especially when scrolled to top).

Fixes #240

### CODE REVIEW

**Comment by eoger** [comment]
Great idea!
However I'm seeing a weird curving on the shadow which is most probably caused by the `.tab-title-wrapper::after` rule.

screen shot 2018-02-17 at 1 14 09 pm

**Comment by eoger** [comment]
I've been fiddling a little bit with CSS and finally found a solution that seems to work: https://github.com/eoger/tabcenter-redux/commit/c5df16f6a9fe29c5500f38799de1ab160f9df8d1.
Does it cover all the edge cases you may have found when you implemented your first version?

**Comment by Keith94** [comment]
Can you add a brief animation for the drop shadow? Or what code can I use?

**Comment by eoger** [comment]
Good suggestion, try this and tell me what you think:
```css
#topshadow {
  transition: box-shadow 0.3s ease-in-out;
}
```

**Comment by Keith94** [comment]
@eoger Looks good to me :+1:

**Comment by eoger** [comment]
We could also follow the Photon design principles and use `cubic-bezier(.07,.95,0,1)`.

**Comment by eoger** [comment]
Merged in https://github.com/eoger/tabcenter-redux/commit/45558bbd933aaab7230688a76ddbd24c1eeb7894, thanks @thomcc and @Keith94 !

**Pull request closed without merging**
